export const actions = {
  product: {
    DATA_FETCHING: "PRODUCT_DATA_FETCHING",
    DATA_FETCHED: "PRODUCT_DATA_FETCHED",
    DATA_EDITED: "PRODUCT_DATA_EDITED",
    DATA_DELETED: "PRODUCT_DATA_DELETED",
    DATA_FETCH_ERROR: "PRODUCT_DATA_FETCH_ERROR",
  },
  category: {
    DATA_FETCHING: "CATEGORY_DATA_FETCHING",
    DATA_FETCHED: "CATEGORY_DATA_FETCHED",
    DATA_FETCH_ERROR: "CATEGORY_DATA_FETCH_ERROR",
    DATA_CREATE: "CATEGORY_DATA_CREATE",
  },
};
